[[local-agent]]
path = "agents/firecrawl"

[[local-agent]]
path = "agents/github"

[[local-agent]]
path = "agents/interface"

[[local-agent]]
path = "agents/climeai"

[[local-agent]]
path = "agents/eventadvisor"

[[local-agent]]
path = "agents/traveladvisor"